# Generated by Django 5.0.14 on 2026-03-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("district", models.CharField(max_length=64)),
                ("subdistrict", models.CharField(blank=True, max_length=64)),
                (
                    "average_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("build_year", models.PositiveIntegerField(blank=True, null=True)),
                ("on_sale_count", models.PositiveIntegerField(default=0)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["district", "name"],
            },
        ),
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(max_length=64)),
                ("task_type", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_level", models.CharField(max_length=32)),
                ("target_name", models.CharField(max_length=120)),
                ("model_name", models.CharField(max_length=64)),
                (
                    "predicted_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_lower",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "confidence_upper",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("features_snapshot", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_platform", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("listing_url", models.URLField(blank=True)),
                ("district", models.CharField(max_length=64)),
                ("subdistrict", models.CharField(blank=True, max_length=64)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("area", models.DecimalField(decimal_places=2, max_digits=8)),
                ("layout", models.CharField(blank=True, max_length=64)),
                ("floor_info", models.CharField(blank=True, max_length=64)),
                ("orientation", models.CharField(blank=True, max_length=64)),
                ("decoration", models.CharField(blank=True, max_length=64)),
                ("build_year", models.PositiveIntegerField(blank=True, null=True)),
                ("elevator", models.CharField(blank=True, max_length=32)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("follow_count", models.PositiveIntegerField(default=0)),
                ("listed_at", models.DateField(blank=True, null=True)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="housing.community",
                    ),
                ),
            ],
            options={
                "ordering": ["-unit_price", "-total_price", "id"],
                "unique_together": {("source_platform", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="PriceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stat_month", models.CharField(max_length=7)),
                ("city", models.CharField(default="Shanghai", max_length=64)),
                ("house_type", models.CharField(default="second_hand", max_length=32)),
                ("size_segment", models.CharField(max_length=64)),
                ("mom_index", models.DecimalField(decimal_places=2, max_digits=8)),
                ("yoy_index", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "ordering": ["stat_month", "size_segment"],
                "unique_together": {
                    ("stat_month", "city", "house_type", "size_segment")
                },
            },
        ),
        migrations.CreateModel(
            name="ListingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="housing.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-id"],
                "unique_together": {("listing", "snapshot_date")},
            },
        ),
    ]
